// Convert a list of {x,y,z} sim waypoints (meters, ENU, origin = geocoded
// address) into a Python script you can run against a real drone (or SITL)
// with DroneKit. The waypoints are converted to absolute lat/lon using the
// terrain origin so the script is location-aware. Altitude is preserved as
// relative-to-takeoff meters.

export function exportDroneKit(waypoints, originLatLon, missionName = 'roboforge_mission') {
  const lines = [];
  lines.push(`# ${missionName}.py`);
  lines.push(`# Auto-generated by RoboForge drone simulator.`);
  lines.push(`# Run against a real vehicle or SITL via DroneKit-Python.`);
  lines.push(`# Install:  pip install dronekit`);
  lines.push(`# Connect:  python3 ${missionName}.py --connect <connection-string>`);
  lines.push(``);
  lines.push(`import argparse`);
  lines.push(`import time`);
  lines.push(`from dronekit import connect, VehicleMode, LocationGlobalRelative`);
  lines.push(`from pymavlink import mavutil`);
  lines.push(``);
  lines.push(`ORIGIN = (${originLatLon.lat.toFixed(7)}, ${originLatLon.lon.toFixed(7)})`);
  lines.push(`METERS_PER_DEG_LAT = 111320.0`);
  lines.push(`import math`);
  lines.push(`def offset_to_latlon(dx_east, dz_north):`);
  lines.push(`    lat0, lon0 = ORIGIN`);
  lines.push(`    dlat = dz_north / METERS_PER_DEG_LAT`);
  lines.push(`    dlon = dx_east / (METERS_PER_DEG_LAT * math.cos(math.radians(lat0)))`);
  lines.push(`    return (lat0 + dlat, lon0 + dlon)`);
  lines.push(``);
  lines.push(`# Recorded waypoints from the simulator (meters, sim ENU):`);
  lines.push(`WAYPOINTS = [`);
  for (const p of waypoints) {
    // Sim convention: x=east, z=north(negative), y=altitude.
    lines.push(`    (${p.x.toFixed(2)}, ${(-p.z).toFixed(2)}, ${p.y.toFixed(2)}),  # east_m, north_m, alt_m`);
  }
  lines.push(`]`);
  lines.push(``);
  lines.push(`def arm_and_takeoff(vehicle, alt):`);
  lines.push(`    while not vehicle.is_armable:`);
  lines.push(`        time.sleep(0.5)`);
  lines.push(`    vehicle.mode = VehicleMode("GUIDED")`);
  lines.push(`    vehicle.armed = True`);
  lines.push(`    while not vehicle.armed:`);
  lines.push(`        time.sleep(0.3)`);
  lines.push(`    vehicle.simple_takeoff(alt)`);
  lines.push(`    while True:`);
  lines.push(`        if vehicle.location.global_relative_frame.alt >= alt * 0.95:`);
  lines.push(`            break`);
  lines.push(`        time.sleep(0.3)`);
  lines.push(``);
  lines.push(`def main():`);
  lines.push(`    ap = argparse.ArgumentParser()`);
  lines.push(`    ap.add_argument("--connect", required=True, help="Vehicle connection string (e.g. udp:127.0.0.1:14550)")`);
  lines.push(`    args = ap.parse_args()`);
  lines.push(`    print("Connecting to", args.connect)`);
  lines.push(`    vehicle = connect(args.connect, wait_ready=True)`);
  lines.push(`    cruise_alt = max(2.0, max((alt for _, _, alt in WAYPOINTS), default=5.0))`);
  lines.push(`    print("Taking off to", cruise_alt, "m")`);
  lines.push(`    arm_and_takeoff(vehicle, cruise_alt)`);
  lines.push(`    for east, north, alt in WAYPOINTS:`);
  lines.push(`        lat, lon = offset_to_latlon(east, north)`);
  lines.push(`        loc = LocationGlobalRelative(lat, lon, max(1.0, alt))`);
  lines.push(`        print(f"-> goto {lat:.6f},{lon:.6f} alt={alt:.1f}")`);
  lines.push(`        vehicle.simple_goto(loc, groundspeed=4.0)`);
  lines.push(`        time.sleep(8)  # crude wait; replace with reach-radius check for production`);
  lines.push(`    print("Mission complete; RTL")`);
  lines.push(`    vehicle.mode = VehicleMode("RTL")`);
  lines.push(`    vehicle.close()`);
  lines.push(``);
  lines.push(`if __name__ == "__main__":`);
  lines.push(`    main()`);
  lines.push(``);
  return lines.join('\n');
}

export function exportJSON(waypoints, originLatLon) {
  return JSON.stringify({
    origin: originLatLon,
    units: 'meters_ENU_relative_to_origin',
    waypoints: waypoints.map(p => ({ x: p.x, y: p.y, z: p.z })),
  }, null, 2);
}
